### ISSUE TITLE
'babel-node' 不是內部或外部命令、可執行的程式或批次檔。 hack3/package.json npm start -> yarn start

### ISSUE THREAD

**Issue by SonicBenz0408** [ntuee-webprogramming/hack3-QAs#1]
助教不好意思，scripts裡面的npm start是否可以改成yarn start? 因為使用npm start會出現 「'babel-node' 不是內部或外部命令、可執行的程式或批次檔。」的錯誤，但使用yarn start則可以正常運作。

**Comment by ntuee-webprogramming** [comment]
可以，這個不會影響批改
