### ISSUE TITLE
dotenv

### ISSUE THREAD

**Issue by pei9733** [ntuee-webprogramming/hack3-QAs#12]
關於第一小題，在mongo.js中寫道「import "dotenv-defaults/config.js";」，然經測試他會產生如下圖的error。但改成「import dotenv from ["dotenv-defaults";」即可解決問題。雖說這部分並沒有標示TODO，但不知是否可以自行改動?

![image](https://user-images.githubusercontent.com/84021157/147518368-fd87ad22-6904-457e-a280-12601f5b69fd.png)

**Comment by ntuee-webprogramming** [comment]
可以改成 import dotenv from "dotenv-defaults";
