### ISSUE TITLE
當yarn add @mui/icons-material: There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by b07508005** [ntuee-webprogramming/hack3-QAs#14]
助教您好 昨天在處理frontend的package時, 會遇到There appears to be trouble with your network connection. Retrying...的問題
yarn add @apollo/client @apollo/react-hooks @emotion/react @emotion/styled @mui/icons-material @mui/lab @mui/material apollo-link-ws graphql moment react-apollo react-beautiful-dnd subscriptions-transport-ws uuid
昨天是依照https://stackoverflow.com/questions/51508364/yarn-there-appears-to-be-trouble-with-your-network-connection-retrying
![image](https://user-images.githubusercontent.com/68584277/147518159-f328df66-4d5c-4ff0-ba64-a9fbcfe607a9.png)
根據Deleting the yarn.lock file and rerunning "yarn install" worked for me.
來處理的
我是直接CTRL+C掉原本的yarn add指令後 跑yarn install
原本以為是解決了 但package貌似沒裝起來
![image](https://user-images.githubusercontent.com/68584277/147518441-4440d780-7a24-44aa-b6d3-9866ccf3b7f4.png)
![image](https://user-images.githubusercontent.com/68584277/147518446-99b94454-18b4-4b93-a4db-fce6e42ad795.png)
總之就是跟@mui/icons-material有關
想問助教這要怎麼解決

註: 原本是yarn add @apollo/client @apollo/react-hooks @emotion/react @emotion/styled @mui/icons-material @mui/lab @mui/material apollo-link-ws graphql moment react-apollo react-beautiful-dnd subscriptions-transport-ws uuid整個會有問題, 然後我剛才一個個試, 才發現是@mui/icons-material的問題, 其他都可以yarn add

**Comment by ntuee-webprogramming** [comment]
解決了嗎？

**Comment by b07508005** [comment]
大概10分鐘前才解決......
原本嘗試透過--network-timeout 100000解決
但還是不行
結果timeout再加個3倍好像差不多
裝了10幾分鐘.......

**Comment by ntuee-webprogramming** [comment]
所以是怎麼解決的？

**Comment by b07508005** [comment]
把timeout再加大3倍
yarn add @mui/icons-material --network-timeout 300000
原本yarn add @mui/icons-material --network-timeout 100000不夠
