### ISSUE TITLE
backend/src/upload.js的process.env.EXAM是不是會去.env.defaults裡面抓？

### ISSUE THREAD

**Issue by dsa66253** [ntuee-webprogramming/hack3-QAs#17]
backend/src/upload.js的process.env.EXAM是不是會去.env.defaults裡面抓？
然後要在env.defaults自己設定EXAM=true?

**Comment by raywu0123** [comment]
請把參數都寫在 .env 裡

**Comment by ntuee-webprogramming** [comment]
.env.defaults 解壓縮後應該會在 backend 資料夾內了，請確認你有沒有

**Comment by ntuee-webprogramming** [comment]
請參考 backend 資料夾中提供的 .env.defaults 來建立你的 .env。換句話說，把 .env.defaults copy 到 .env 之後，根據 pre-README 把 MONGO_URL 填入適當的值 (i.e. 你的 DB 連結)。

另外，記得不要把 .env push 到 GitHub！！請把 .env 加到 .gitignore。助教在批改時會使用自己的 .env 以及 DB。

**Comment by Kevin-Shiuan** [comment]
後端未提供.env.defaults ，解壓縮後沒有看到

**Comment by Kevin-Shiuan** [comment]
目前的解決方法是自行添加EXAM = true

**Comment by ntuee-webprogramming** [comment]
ref code 解壓縮後 backend 資料夾內會有，若沒有看到可能是因為你用資料夾打開，那預設可能會**看不到**隱藏檔案，而不是**沒有**。

**Comment by Kevin-Shiuan** [comment]
解決，謝謝！
