### ISSUE TITLE
yarn test跑不動

### ISSUE THREAD

**Issue by chen77526** [ntuee-webprogramming/hack3-QAs#18]
![image](https://user-images.githubusercontent.com/55378273/147518686-c49bf4a5-d7a8-47a8-a561-12b53d6c6b3a.png)

助教們好：
       因為在稍早有將backend的package.json加上 "type":"module"，好像導致這個問題，不知道哪一個bug要先處理。

更新：
![image](https://user-images.githubusercontent.com/55378273/147518742-314b2245-304a-4ce0-ab7a-94bd78191bcd.png)

**Comment by ntuee-webprogramming** [comment]
那請不要用 "type": "modules"，後端的部分可以用 babel 去執行

**Comment by chen77526** [comment]
@ntuee-webprogramming 
剛剛沒有用"type": "modules"出現以下畫面
![image](https://user-images.githubusercontent.com/55378273/147519814-c8703292-51a3-42de-9fe4-0c27469f9105.png)
backend的package.json
![image](https://user-images.githubusercontent.com/55378273/147520033-c7dd1429-ae1f-464f-926a-9df03e55d469.png)

**Comment by ntuee-webprogramming** [comment]
你是不是沒有 .babelrc?

**Comment by chen77526** [comment]
沒問題了，一開始測試有放但跑不起來...

**Comment by chen77526** [comment]
非常感謝
