### ISSUE TITLE
做mutation createTask時前端噴subscription錯誤

### ISSUE THREAD

**Issue by vwvwMM** [ntuee-webprogramming/hack3-QAs#22]
我在做第四題時，用後端測過gql的寫法沒什麼問題，可以成功create，但是放到前端他的console錯跟我說subscriptionObserver有錯，這表示subscription的code出錯了嗎?
![image](https://user-images.githubusercontent.com/71827661/147519485-ef6dab6c-bcba-4ea1-a42e-e30bc8ff690e.png)

**Comment by ntuee-webprogramming** [comment]
請自己 debug 哦！
