### ISSUE TITLE
uncomment line18 "link: splitLink," 後出現白畫面

### ISSUE THREAD

**Issue by clins210** [ntuee-webprogramming/hack3-QAs#23]
請問已參考連結指示參考code加入const splitLink Function
但在uncomment line18 "link: splitLink," 後出現白畫面

（在uncomment line18前是可看到專案框架內容的畫面的）

應該往哪個方向先處理QQ

**Comment by ntuee-webprogramming** [comment]
先試試 console.log()

**Comment by clins210** [comment]
找到問題，已解決，謝謝！
