### ISSUE TITLE
cypress和gradescope的public test是否一致？

### ISSUE THREAD

**Issue by BingChengChiang** [ntuee-webprogramming/hack3-QAs#24]
如題，我在cypress上測試，1-1 1-2 2 3 的public test都有過，但gradescope上都是fail。

**Comment by jc-hiroto** [comment]
同問，cypress all pass 但 gradescope 都是 FAIL.

**Comment by raywu0123** [comment]
可以給我你們的名字嗎
我從後台看看

**Comment by jc-hiroto** [comment]
張博皓 B07505032

**Comment by BingChengChiang** [comment]
江秉城 b09901044

**Comment by raywu0123** [comment]
看不太出來原因QQ
但是 public test 是一樣的
private test 測的項目也都一樣只是換資料

**Comment by jc-hiroto** [comment]
目前測試依然全 fail，請問這種狀況是否可要求助教使用 cypress 批改？

**Comment by jc-hiroto** [comment]
我這邊是 node v16.13.1 跑在 macOS + firefox:dev browser
不知道跟環境有沒有關係？

**Comment by ntuee-webprogramming** [comment]
已更新 Gradescope image. 請各位再試試看。

**Comment by BingChengChiang** [comment]
目前沒問題了！
感謝
