### ISSUE TITLE
localhost:5000 address always in use issues

### ISSUE THREAD

**Issue by warronyiang15** [ntuee-webprogramming/hack3-QAs#27]
Hi,

我的local端的5000 address會一直顯示正在使用，在做作業時也是出現這種情況，所以我每次都將5000改寫成4000，但是這次的cypress BACKEND_URL 寫死成 5000 造成test無法通過，請問我能修改嗎？ 其次是繳交的時候可以寫成是4000嗎？還是一定要改回來？

謝謝

**Comment by ntuee-webprogramming** [comment]
請參考 #4

**Comment by warronyiang15** [comment]
感謝教授 and TA ，已解決
