### ISSUE TITLE
gradscope 上傳有寫 submitted 就是成功沒錯吧

### ISSUE THREAD

**Issue by brianw0924** [ntuee-webprogramming/hack3-QAs#28]
想確認一下！
上面 status 寫 submitted ！
點進去 hack 3 裡面有顯示分數！
這樣就是有成功沒錯吧！
還是有需要另外做什麼選取的動作！？（我目前只上傳一次，點 History 裡面有寫 Activate）
謝謝！

**Comment by ntuee-webprogramming** [comment]
是的。不用
