### ISSUE TITLE
Yarn backend 顯示 'babel-node' 不是內部或外部命令、可執行的程式或批次檔。

### ISSUE THREAD

**Issue by jasperchan5** [ntuee-webprogramming/hack3-QAs#3]
<img width="386" alt="螢幕擷取畫面 2021-12-28 091630" src="https://user-images.githubusercontent.com/81878263/147517392-c540c2a0-ab9f-41d5-b69b-5d0836bdb14b.png">

如圖，請問這要如何解決?

**Comment by raywu0123** [comment]
請參考 https://github.com/ntuee-webprogramming/hack3-QAs/issues/1
