### ISSUE TITLE
無法dataInit

### ISSUE THREAD

**Issue by chunhan1928** [ntuee-webprogramming/hack3-QAs#32]
db有連上了，就是不知道為什麼沒辦法跑動dataInit()，不會console.log("Database initialized!")，當然db裡面也沒東西
有試著把它放在db.once()過，但沒用

**Comment by chinyi0523** [comment]
先參考#19

**Comment by chunhan1928** [comment]
參考過了，應該不相關，我完全沒有error，就是很莫名的沒辦法dataInit()
已經有
The server is up on port 5000!
MongoDB connected!
但就是沒辦法
Database initialized!

**Comment by chunhan1928** [comment]
沒事，我沒有裝到.env.defaults，問題解決
