### ISSUE TITLE
export 'parse' (imported as 'parse') was not found in 'graphql' (module has no exports)

### ISSUE THREAD

**Issue by Idonotwant** [ntuee-webprogramming/hack3-QAs#33]
在frontend npm start 後噴了很多類似的問題，不知道怎麼解決

![image](https://user-images.githubusercontent.com/75072942/147520233-12e1fdf1-9b0c-4070-bea0-4215781ec5f7.png)

**Comment by ntuee-webprogramming** [comment]
先 comment out 掉一些自己的 code, 確定是不是自己的 code 哪裡寫錯 (typo)?

**Comment by Idonotwant** [comment]
我是解壓縮完後就npm start了，還沒寫東西

**Comment by ntuee-webprogramming** [comment]
參考 https://github.com/apollographql/react-apollo/issues/922 是不是漏裝graphql ?

**Comment by Idonotwant** [comment]
已經裝了，還是不行
我還有以下這個問題
不知道是不是跟這個有關?
![image](https://user-images.githubusercontent.com/75072942/147522177-ed1d36e5-1275-470b-91ba-2536085dcc6b.png)

https://giters.com/solana-labs/wallet-adapter/issues/200

**Comment by ntuee-webprogramming** [comment]
那你的 package.json 有這行嗎？

“type":"module"

有裝 babel 的話，這行可以先拿掉試試看

**Comment by Idonotwant** [comment]
一開始就沒有那行

**Comment by ntuee-webprogramming** [comment]
請進入meet連結: https://meet.google.com/ume-zgrb-upf

**Comment by ntuee-webprogramming** [comment]
已解決

**Comment by Idonotwant** [comment]
請問可以加長時間嗎?只是問一下==

**Comment by ntuee-webprogramming** [comment]
請問你的學號與姓名？

**Comment by Idonotwant** [comment]
B09901102 陳威儒

**Comment by ntuee-webprogramming** [comment]
那讓你延長到 12:40pm

**Comment by Idonotwant** [comment]
謝謝

**Comment by ntuee-webprogramming** [comment]
你在 12:40pm 之前記得要去 submit Gradescope 哦！
