### ISSUE TITLE
GradeScope debugging

### ISSUE THREAD

**Issue by jc-hiroto** [ntuee-webprogramming/hack3-QAs#42]
B07505032 張博皓

雖然已經留過言但還是上來回報一下。
local test 都過了，排除 code 問題後目前已嘗試過：
1. 確認 file structure 一致
2. Archive zip file 解開後跑 cypress無問題
1. 已重新 yarn 安裝所有套件
2. 已嘗試使用 macOS + Windows 來 `git archive`

都還是 fail ，希望提供資訊給助教比較好查到問題。

**Comment by ntuee-webprogramming** [comment]
剛剛已更新 Gradescope image. 請再試試看。

**Comment by jc-hiroto** [comment]
最後一次 Submission 已變成 All PASS，謝謝老師與助教。
