### ISSUE TITLE
第四題input更動

### ISSUE THREAD

**Issue by vwvwMM** [ntuee-webprogramming/hack3-QAs#43]
我第四題在前端的這個函式中如果把input這層拿掉，直接輸入各props就可以順利create，，cypress上也有通過，那請問我可以拿掉嗎?
![image](https://user-images.githubusercontent.com/71827661/147523475-45ae7843-c62d-4b1e-9cce-2ac2155c8e95.png)

**Comment by ntuee-webprogramming** [comment]
不行。這個應該是你的 query 寫錯了，請自行檢查一遍。
