### ISSUE TITLE
Q5 需要動到frontend嗎?

### ISSUE THREAD

**Issue by pyshen-wilson** [ntuee-webprogramming/hack3-QAs#44]
如題，我依造instruction改了Mutation.js 和schema了
DB也是正常work，但frontend卻沒有即時刪除task，需要重新整理才會真的刪掉
所以這題是純backend還是有需要改frontend?

**Comment by lydia7635** [comment]
路過回，Q6 才會需要實作刪除的 subscription 喔，所以是正常的

**Comment by pyshen-wilson** [comment]
但是我放到gradescope上顯示FAILED...

**Comment by stanthemaker** [comment]
同上， 我的Todo5 實作完，Todo 6還沒，yarn test也通過，但是繳交上去卻fail。
b09901104翁瑋杉

**Comment by ntuee-webprogramming** [comment]
請問你們有先 commit 再打包嗎？

**Comment by stanthemaker** [comment]
有了，我commit 之後，再打包成zip上傳就有了。謝謝老師

**Comment by pyshen-wilson** [comment]
回助教: 我也是有commit再打包，但還是沒過

**Comment by raywu0123** [comment]
@pyshen-watson 請問你的姓名? 我幫你從後台看看

**Comment by pyshen-wilson** [comment]
不好意思，我有地方耍笨了，現在過了
