### ISSUE TITLE
自行修改 backend 的 PORT

### ISSUE THREAD

**Issue by Kevin-Shiuan** [ntuee-webprogramming/hack3-QAs#5]
電腦本身就有系統佔用 PORT 5000, 自行更改 backend 的 PORT 成 4000，需要另外註明嗎？

**Comment by ntuee-webprogramming** [comment]
若是 Mac 可以參考 https://developer.apple.com/forums/thread/682332 把 5000 關掉
自動測試都是用 localhost:5000 去測試，所以最好請還是改成 5000 上傳

**Comment by ntuee-webprogramming** [comment]
解決了嗎？

**Comment by Kevin-Shiuan** [comment]
解決了，謝謝！
